### ISSUE TITLE
Optimization: Remove extra $bool calls

### ISSUE THREAD

**Issue by wavebeem** [squiggle-lang/squiggle-lang#117]
There are a handful of situations where values are known to be boolean, so we can remove calls to $bool.

All of the comparison operators: `not is has > < >= <= == !=`.

I think the best plan for optimizations might be to have a separate step for optimizations of the ES AST, rather than trying to handle optimizations that may affect many sections of the compiler.

Also could work on code of the form:

``` javascript
$bool($bool(x) && $bool(y))
$bool($bool(x) || $bool(y))
```

Example:

``` javascript
if ($bool($eq($ref(x, "x"), 4))) { ... }
```

can become

``` javascript
if ($eq($ref(x, "x"), 4)) { ... }
```

**Comment by Heimdell** [comment]
You could try do type inference for that - it will allow you to optimize out even user-declared functions if they are guaranteed to return things of $bool, $number or $string type.

**Comment by wavebeem** [comment]
It's definitely something to consider eventually.
