### ISSUE TITLE
Add CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by wavebeem** [squiggle-lang/squiggle-lang#144]
I should list the contributors out in a file. It would be a nice way to thank them.

This command should make it easy to find them:
```bash
git log --format=email | grep From: | sed 's/From: //' | sort | uniq
```

**Comment by wavebeem** [comment]
@gutsy @DylanLWScott @noahmorrison @rdenmark 

I have the following entries for y'all per that git command:

```
"Todd M. Guerra" <toddguerra@gmail.com>
Dylan Scott <drrscott@hotmail.com>
Roby Denmark <roby@janrain.com>
noah morrison <noah@morrison.ph>
```

Please reply here and I'll add you to the list.

**Comment by rdenmark** [comment]
That works for me.

**Comment by gutsy** [comment]
Looks good!

**Comment by DylanLWScott** [comment]
:+1:

**Comment by noahmorrison** [comment]
Fine with me

**Comment by wavebeem** [comment]
All right, you've all been added. Thanks for your help, folks!
