### ISSUE TITLE
Switch to Babel compatible ES6-ish modules

### ISSUE THREAD

**Issue by wavebeem** [squiggle-lang/squiggle-lang#158]
It's entirely possible people are gonna want to mix ES6 code and Squiggle code together, or use libraries that export ES6 modules, so we should probably export our stuff with the `__esModule` flag or something, and I guess support importing ES6 modules too?

Note: this will require the compiler to be smart about identifier references and know when they're actually cross module references so they can be compiled differently to support cyclic module situations.

```
import "foo" as Foo # default import
import "bar" (quux, ducks) # named imports
import "baz" (quux as bazQuux) # renaming import
```

Yes I know this is backwards from ES6 syntax, but I think it reads better this way. Maybe it should support `*` imports and combined default and named importing together, though both of those seem fairly unimportant right now.

```
export foo # named export
export foo as myFoo # renaming export
export default myMainFunction # default export
```

This syntax is a little different than ES6 since ES6 wants braces around named exports like that, and we _will not_ support exporting a definition directly.

Also, the built-in `require` keyword should be dropped after adding this support in.

**Comment by wavebeem** [comment]
Side note: using `as` as a keyword makes me sad because then you can't use `f(as, bs)` for two lists, but no other word makes sense there. I could use an arrow `=>` but idk. I definitely want to avoid syntax that confuses it with objects, though, hence the parentheses over braces.

**Comment by wavebeem** [comment]
This also opens up the possibility of compiling to AMD format instead, if people really want that still...

**Comment by wavebeem** [comment]
Probably worth keeping handy: http://www.2ality.com/2015/12/babel-commonjs.html

**Comment by krainboltgreene** [comment]
Okay, I like the backwardsness. It reads a little better.....EXCEPT when you need to do this:

``` javascript
import {activities} from "../../../../activities"
```

Which looks like this

``` squiggle
import "../../../../activities" as (activities)
```

**Comment by wavebeem** [comment]
Actually that reminds me of something I was unclear on from perusing the spec and related blog posts: are module strings relative to the module importing them? or how do the paths work on that?

Also I agree it's a bit of an eyesore there, but I think both cases are pretty awful.

Also it means that it's a little easier to grep for imports.

**Comment by krainboltgreene** [comment]
Essentially: No.

Realistically: Sortive? It's based on a subsystem that handles lookup.

**Comment by wavebeem** [comment]
Question: how does this interact with REPL mode? :\

I think ideally you could run `:r` or `:reload` to clear the CommonJS cache and re-require everything? But the proper handling of named imports doesn't make as much sense at the REPL level…

**Comment by wavebeem** [comment]
Interestingly, here's how `babel-node` handles modules...

```
> import L from "lodash"
SyntaxError: repl: Modules aren't supported in the REPL
```

**Comment by krainboltgreene** [comment]
Yeeeeeeeeeeeep.

**Comment by wavebeem** [comment]
Ohh… people will probably expect to be able to import their Squiggle modules through this, but that will be difficult since we need to compile them too… could hijack require or something? Blergh.

**Comment by wavebeem** [comment]
Additional can of worms: attempting to statically verify named imports.
